---
- hosts: all
  become: true
  tasks:

  - name: install apache and php packages
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php }}"
      state: latest
      update_cache: yes